import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

// Use the Inter font family for a clean, modern look across the app
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // Apply Inter font and a soft gradient background
        className={`${inter.variable} antialiased bg-gradient-to-br from-indigo-50 via-purple-50 to-blue-50 min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
